name: Classic CI/CD

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: install golangci-lint
        run: |
          curl -sSfL \
            https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            | sh -s -- -b $(go env GOPATH)/bin v1.30.0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --rm-dist --snapshot

      - name: Upload terraform provider
        uses: actions/upload-artifact@v2
        with:
          name: provider
          path: dist/*
